/*
 * File: app/view/MyNavigationView.js
 *
 * This file was generated by Sencha Architect version 4.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TxGMobi.view.MyNavigationView', {
    extend: 'Ext.navigation.View',
    alias: 'widget.mynavigationview',

    requires: [
        'TxGMobi.view.MyNavigationViewViewModel',
        'TxGMobi.view.MyTabPanel',
        'Ext.tab.Panel',
        'Ext.navigation.Bar',
        'Ext.Button'
    ],

    config: {
        viewModel: {
            type: 'mynavigationview'
        },
        items: [
            {
                xtype: 'mytabpanel'
            }
        ],
        navigationBar: {
            docked: 'top',
            items: [
                {
                    xtype: 'button',
                    align: 'right',
                    ui: 'plain',
                    iconCls: 'x-fa fa-search'
                }
            ]
        }
    }

});