/*
 * File: app/view/MyTabPanel.js
 *
 * This file was generated by Sencha Architect version 4.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TxGMobi.view.MyTabPanel', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.mytabpanel',

    requires: [
        'TxGMobi.view.MyTabPanelViewModel',
        'Ext.SegmentedButton',
        'Ext.Button',
        'Ext.Label',
        'Ext.XTemplate',
        'Ext.dataview.List',
        'Ext.tab.Bar'
    ],

    config: {
        viewModel: {
            type: 'mytabpanel'
        },
        items: [
            {
                xtype: 'container',
                title: 'Talks',
                iconCls: 'x-fa fa-info',
                scrollable: false,
                layout: 'vbox',
                items: [
                    {
                        xtype: 'segmentedbutton',
                        defaults: {
                            flex: 1
                        },
                        items: [
                            {
                                xtype: 'button',
                                text: 'MyButton1'
                            },
                            {
                                xtype: 'button',
                                text: 'MyButton2'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        minHeight: 150,
                        items: [
                            {
                                xtype: 'label',
                                tpl: [
                                    '<h2>{author}</h2>',
                                    '<h4>{title}</h4>'
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'list',
                        flex: 1,
                        itemTpl: [
                            '<div style=background:url({image})>',
                            '    <div>',
                            '        <h2>{author}</h2>',
                            '        <h4>{title}</h4>',
                            '    </div>',
                            '</div>'
                        ],
                        store: 'TalkStore',
                        onItemDisclosure: true
                    }
                ]
            },
            {
                xtype: 'container',
                title: 'Tab 2',
                iconCls: 'x-fa fa-info'
            },
            {
                xtype: 'container',
                title: 'Tab 3',
                iconCls: 'x-fa fa-info'
            },
            {
                xtype: 'container',
                title: 'Tab 3',
                iconCls: 'x-fa fa-info'
            },
            {
                xtype: 'container',
                title: 'Tab 3',
                iconCls: 'x-fa fa-info'
            }
        ],
        tabBar: {
            cls: 'z-tabbar',
            docked: 'bottom',
            defaults: {
                iconAlign: 'top'
            }
        }
    }

});